updated gottcha2 to use fungal database
microbiomedata/ReadbasedAnalysis pull request #21
Opened 2024-06-11 17:17 UTC by mflynn-lanl

2024-06-11 21:53 UTC, aclum requested changes
The new path doesn't exist at nersc. Please update to the correct path and provide test workflow output. I think perhaps you wanted to /refdata/gottcha2_fungal/GOTTCHA2_fungal/gottcha_db.BAVFPt.species.fna

2024-06-11 22:07 UTC, mflynn-lanl commented
I will replace the files in /refdata/gottcha2/ with the files in /refdata/gottcha2_fungal/GOTTCHA2_fungal/. this way there aren't old, unused files cluttering the file system
________________________________
From: aclum ***@***.***>
Sent: Tuesday, June 11, 2024 3:53 PM
To: microbiomedata/ReadbasedAnalysis ***@***.***>
Cc: Flynn, Mark C ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microbiomedata/ReadbasedAnalysis] updated gottcha2 to use fungal database (PR #21)


@aclum requested changes on this pull request.

The new path doesn't exist at nersc. Please update to the correct path and provide test workflow output. I think perhaps you wanted to /refdata/gottcha2_fungal/GOTTCHA2_fungal/gottcha_db.BAVFPt.species.fna

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/microbiomedata/ReadbasedAnalysis/pull/21*pullrequestreview-2111513975__;Iw!!Bt8fGhp8LhKGRg!AfjVzN_2e8OahzK4ryDHRpsVbgpIhhfYPCpyCnsVtymLhsy_WDAAhMXHzHDjIAhogwDwdq2d_SzarHw1ThU5Y5Cp$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AEXIUF7FUDCOOI7JOK2GHO3ZG5WWXAVCNFSM6AAAAABJEYM4QSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMJRGUYTGOJXGU__;!!Bt8fGhp8LhKGRg!AfjVzN_2e8OahzK4ryDHRpsVbgpIhhfYPCpyCnsVtymLhsy_WDAAhMXHzHDjIAhogwDwdq2d_SzarHw1Tlr9V4J4$>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-06-11 23:35 UTC, mflynn-lanl commented
I moved:
/global/cfs/cdirs/m3408/refdata/gottcha2​ to /global/cfs/cdirs/m3408/refdata/gottcha2_old​
and
/global/cfs/cdirs/m3408/refdata/gottcha2_fungal/GOTTCHA2_fungal​ to /global/cfs/cdirs/m3408/refdata/gottcha2​

________________________________
From: aclum ***@***.***>
Sent: Tuesday, June 11, 2024 3:53 PM
To: microbiomedata/ReadbasedAnalysis ***@***.***>
Cc: Flynn, Mark C ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microbiomedata/ReadbasedAnalysis] updated gottcha2 to use fungal database (PR #21)


@aclum requested changes on this pull request.

The new path doesn't exist at nersc. Please update to the correct path and provide test workflow output. I think perhaps you wanted to /refdata/gottcha2_fungal/GOTTCHA2_fungal/gottcha_db.BAVFPt.species.fna

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/microbiomedata/ReadbasedAnalysis/pull/21*pullrequestreview-2111513975__;Iw!!Bt8fGhp8LhKGRg!AfjVzN_2e8OahzK4ryDHRpsVbgpIhhfYPCpyCnsVtymLhsy_WDAAhMXHzHDjIAhogwDwdq2d_SzarHw1ThU5Y5Cp$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AEXIUF7FUDCOOI7JOK2GHO3ZG5WWXAVCNFSM6AAAAABJEYM4QSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMJRGUYTGOJXGU__;!!Bt8fGhp8LhKGRg!AfjVzN_2e8OahzK4ryDHRpsVbgpIhhfYPCpyCnsVtymLhsy_WDAAhMXHzHDjIAhogwDwdq2d_SzarHw1Tlr9V4J4$>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-06-13 17:40 UTC, aclum approved these changes

2024-06-13 17:41 UTC, merged